; PlatformIO Project Configuration File

; =============================================================
; Section commune à tous les environnements
; =============================================================
[common]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
lib_deps = 
    yhadji/Capsule@^1.0.3
    paulo-raca/Buffered Streams@^1.0.8
    sandeepmistry/LoRa@^0.8.0
    adafruit/Adafruit NeoPixel@^1.11.0
    tobiasschuerg/ESP8266 Influxdb@^3.13.1
monitor_speed = 115200
build_flags =
    -D RF_PROTOCOL_ICARUS
    -I src/ERT_RF_Protocol_Interface

; =============================================================
; Environnements spécifiques
; =============================================================

[env:uplink]
extends = common
build_flags =
    ${common.build_flags}
    -D UPLINK

[env:av_downlink]
extends = common
build_flags =
    ${common.build_flags}
    -D AV_DOWNLINK

[env:gse_downlink]
extends = common
build_flags =
    ${common.build_flags}
    -D GSE_DOWNLINK
